services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb:inception
    init: true
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - docker-network
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress:inception
    init: true
    restart: always
    env_file: .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
      - WORDPRESS_EMAIL=${WORDPRESS_EMAIL}
    volumes:
      - wordpress:/var/www/html
    networks:
      - docker-network
    expose:
      - "9000"
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx:inception
    init: true
    restart: always
    env_file: .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/html
    networks:
      - docker-network
    ports:
      - "443:443"
    depends_on:
      - wordpress

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
networks:
  docker-network:
    name: docker-network
    driver: bridge